sudo: false

language: java
jdk:
  - oraclejdk8
env:
  global:
    - secure: "REsW0g3DzR33QZFd6nhwNS3jMxC9VTXRxmm6X63JIaXPHANgytll1Bm7TUrnrlm+Jep2VSedebh+t/WBvQp1WUjbXxCUlgnUykSCZvb37YZ+J8ecJxPf/cVcZjzft2fqeD9x9eD9CGgL0nkdulturc+gaTHr0Yqp4USbkGgtSH1gB2S/OhTCJpX+pCNwT5Cvp97jXs47TMR3lh6vCqRtcZVLn4sivRsb+VKOdFp+MJsCf2/yCVBKXBsmbkAoPnZnvtRjtmo00UoyzRhwJEigFp5jN/h8koxl2UMmz27xRxnR/EVp+uPBHCO3ySUWNnlxSqhFzROgqi0i5Ea0Snk8w2b9L2AC9kU/VI58E8/kEGjbNb1B1fwNt8Z+CNdrG2eYkeUXzw3oSaOca5wIja2qRU8Gy3tFwnNrUwdFxP8BTOHKO3Eb3Jva0PObie9PRdfslVW77ONQVH0d2q4hcU9itJBaZlnPrsEBsOCdFrpKufQ9c0EDd0+YcFuKaiGzda9+gKmQNf3mIGPPa9I0PE6sOUrthptGWfbe4Xhgubw0aw272a3wPH6HRblitUuTJpfZwwq4/EU5SfWvwha4Nxz6i7wpFfzYswkNe9WyhLfRSshwcKGopw292JBV+ZMgXc+BLT6elRGjvSK04sFcmOrFnX5LEaU4UMIRMnfdDSTl418="
cache:
  directories:
    - $HOME/.m2
  
script: 
  - "mvn cobertura:cobertura"
  - "mvn javadoc:javadoc"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash Deploy_JavaDoc.sh

notification:
  email:
    on_success: never
    on_failure: always
