version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx512m
    steps:
      - checkout
      - restore_cache:
          keys:
            - VTerminal-dependencies-{{ checksum "pom.xml" }}
            - VTerminal-dependencies-
      - run: mvn clean install -U
      - save_cache:
          paths:
            - ~/.m2
          key: VTerminal-dependencies-{{ checksum "pom.xml" }}
      - run: mvn integration-test
      - store_test_results:
          path: target/surefire-reports